### ISSUE TITLE
Important Notice

### ISSUE THREAD

**Issue by IntegerBytes** [LEGENDXOP/LEGEND-BOT#36]
Heya listen, I am from India and I have found a repository named legend userbot actually I was helping in making that repository but the owner is not giving credits to me and you. He is saying he will not give credits he also kicked me from his repository. I want you to handle this by giving DMCA takedown Notice on this repository. heya Friend help me please Repository Link https://github.com/LEGEND-OS/LEGENDUSERBOT, https://github.com/LEGEND-OS/LegendBot-Addons

It's kanged of Legend bot and UltraX

@LEGENDXOP @lucifeermorningstar @PROBOYX

**Comment by LEGENDXOP** [comment]
Dm me on Telegram link = https://t.me/LEGENDX22

**Comment by IntegerBytes** [comment]
Actually I m not on telegram

**Comment by LEGENDXOP** [comment]
Okay

**Comment by IntegerBytes** [comment]
Sir kindly help me by giving dmca @LEGENDXOP

**Comment by LEGENDXOP** [comment]
Ok, I will. Tomorrow I will

**Comment by IntegerBytes** [comment]
Sure

**Comment by IntegerBytes** [comment]
@LEGENDXOP Give you gave DMCA if kindly send ScreenShot

**Comment by LEGENDXOP** [comment]
Today I am busy I'll give DMCA tomorrow

**Comment by IntegerBytes** [comment]
Sure
